#if !defined(KEY_LIST_H)


typedef u32 Key;
enum 
{
	Key_Unknown       ,
    Key_Space         ,
    Key_Apostrophe    ,
    Key_Comma         ,
    Key_Minus         ,
    Key_Period        ,
    Key_Slash         ,
    Key_0             ,
    Key_1             ,
    Key_2             ,
    Key_3             ,
    Key_4             ,
    Key_5             ,
    Key_6             ,
    Key_7             ,
    Key_8             ,
    Key_9             ,
    Key_Semicolon     ,
    Key_Equal         ,
    Key_A             ,
    Key_B             ,
    Key_C             ,
    Key_D             ,
    Key_E             ,
    Key_F             ,
    Key_G             ,
    Key_H             ,
    Key_I             ,
    Key_J             ,
    Key_K             ,
    Key_L             ,
    Key_M             ,
    Key_N             ,
    Key_O             ,
    Key_P             ,
    Key_Q             ,
    Key_R             ,
    Key_S             ,
    Key_T             ,
    Key_U             ,
    Key_V             ,
    Key_W             ,
    Key_X             ,
    Key_Y             ,
    Key_Z             ,
    Key_LeftBracket   ,
    Key_Backslash     ,
    Key_RightBracket  ,
    Key_GraveAccent   ,
    Key_World_1       ,
    Key_World_2       ,
    Key_Escape        ,
    Key_Enter         ,
    Key_Tab           ,
    Key_Backspace     ,
    Key_Insert        ,
    Key_Delete        ,
    Key_Right         ,
    Key_Left          ,
    Key_Down          ,
    Key_Up            ,
    Key_PageUp        ,
    Key_PageDown      ,
    Key_Home          ,
    Key_End           ,
    Key_CapsLock      ,
    Key_ScrollLock    ,
    Key_NumLock       ,
    Key_PrintScreen   ,
    Key_Pause         ,
    Key_F1            ,
    Key_F2            ,
    Key_F3            ,
    Key_F4            ,
    Key_F5            ,
    Key_F6            ,
    Key_F7            ,
    Key_F8            ,
    Key_F9            ,
    Key_F10           ,
    Key_F11           ,
    Key_F12           ,
    Key_F13           ,
    Key_F14           ,
    Key_F15           ,
    Key_F16           ,
    Key_F17           ,
    Key_F18           ,
    Key_F19           ,
    Key_F20           ,
    Key_F21           ,
    Key_F22           ,
    Key_F23           ,
    Key_F24           ,
    Key_F25           ,
    Key_KP_0          ,
    Key_KP_1          ,
    Key_KP_2          ,
    Key_KP_3          ,
    Key_KP_4          ,
    Key_KP_5          ,
    Key_KP_6          ,
    Key_KP_7          ,
    Key_KP_8          ,
    Key_KP_9          ,
    Key_KP_Decimal    ,
    Key_KP_Divide     ,
    Key_KP_Multiply   ,
    Key_KP_Subtract   ,
    Key_KP_Add        ,
    Key_KP_Enter      ,
    Key_KP_Equal      ,
    Key_LeftShift     ,
    Key_LeftControl   ,
    Key_LeftAlt       ,
    Key_LeftSuper     ,
    Key_RightShift    ,
    Key_RightControl  ,
    Key_RightAlt      ,
    Key_RightSuper    ,
    Key_Menu          ,
	// Keys are over, here are mouse buttons!
	Key_MouseLeft,
	Key_MouseMiddle,
	Key_MouseRight,
	Key_MouseSideTop,
	Key_MouseSideBottom,

    Key_Count         ,
};

// @NOTE(hl): Problem with having keyboard and mouse keys in one enum is that we cant properly enumerate them
// So we store first mouse, so we can
#define FIRST_MOUSE_BUTTON  (Key_MouseLeft)
#define LAST_MOUSE_BUTTON   (Key_MouseSideBottom)
#define MOUSE_BUTTON_COUNT  (LAST_MOUSE_BUTTON - FIRST_MOUSE_BUTTON + 1)


#define KEY_LIST_H 1
#endif
